### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by sdeschamps-orange** [Orange-OpenSource/Orange-Confort-plus#15]
Add a keyboard shortcut (the best would be if we can choose/change it) to activate/deactivate Confort+

**Comment by Thomas-Ringot** [comment]
If you use chrome, you can already do this:

-  Type `chrome://extensions` in the address bar
- Scroll down 'til You see a link `Keyboard shortcuts`
- Find `Orange-confort-plus` then assign the keyboard shortcut you want

**Comment by notabene** [comment]
More precisely (thank you @liyokuna who asked me eactly the expected behaviour),

1. **Discoverability: add an item in the Tools menu** that triggers Confort+'s insertion/removal in the page (the same as what the button does)
2. **Keyboard shortcut** with the same behaviour

Optimally the keyboard shortcut should be configurable (in the case of potential conflicts, it is very useful to reassign keyboard shortcuts).

**Comment by liyokuna** [comment]
Hello, @notabene 
I just find a way to add a global shortcut, to trigger the extension from whatever tab you are on.
The thing is that shortcut can be modify by the user. He have to go to this chrome://extensions/shortcuts links to do so. We can't save that value, our value is defined as a default.
I will add a text to explain that in the  help pages.
[https://github.com/Orange-OpenSource/Orange-Confort-plus/commit/73e383b7f06429a362d43d2f52d189f1ecb5d1d0](shortcut)
