### ISSUE TITLE
Feature request: refrain from setting UCI42 cookie

### ISSUE THREAD

**Issue by RavanH** [Orange-OpenSource/Orange-Confort-plus#250]
Hi, when running the web (serveur) script files on a website, the script sets one initial cookie "UCI42" and even though it is a functionality cookie, strictly speaking I'd need to block this from being set before any consent is given.

Would it be at all possible to do without this initial cookie and only set cookies when the visitor actually changes/saves toolbar settings? This would make it possible to load the script before consent is obtained...

**Comment by ffoodd** [comment]
Hi, thanks for opening an issue.

As far as I know, Confort+ doesn't store any personal data in its cookies, which are required for the plugin to work.

There's no need for consent in such case.

Moreover if you're hosting and serving Confort+ by yourself, consent is on your side: you may want to only inject and load Confort+ when you obtained user consent.

I can't see any way for Confort+ to wait for consent since there are dozens different ways for a website to handle consent and cookies. That just can't be reliable.

By the way, we're working on the next major release that will leverage `localStorage` instead of cookies, so we're unlikely add a feature related to cookies in the current release.

I'm closing this as a won't fix, but feel free to continue the discussion.

**Comment by RavanH** [comment]
Hi @ffoodd 

> Moreover if you're hosting and serving Confort+ by yourself, consent is on your side: you may want to only inject and load Confort+ when you obtained user consent.

That is indeed what I'm doing now :)

I did not expect a fix for this version, I was just suggesting that the toolbar could do without that initial "UCI42" cookie value "0|0|0". Not setting a cookie at first load, could that not be the same as setting a cookie with zero as value? And maybe similar for localStorage in the new version?

Anyway, thanks for considering :)
